### ISSUE TITLE
Application does not support Subpaths with domain name

### ISSUE THREAD

**Issue by kwadroke** [desbma/gotify-desktop#1]
Application shuts down when using a subpath for the domain via a reverse proxy, via the instructions from here: https://gotify.net/docs/nginx#at-a-subpath. Domain is configured with SSL (port 443) at https://EXAMPLE.com/gotify

It runs fine until a message is received. 

Output
```
INFO  [gotify_desktop] Connected to wss://EXAMPLE.com/gotify/stream
thread 'main' panicked at 'Failed to get message: HTTP status client error (404 Not Found) for url (https://EXAMPLE.com/application)', src/main.rs:21:40
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Aborted
```

My ~/.config/gotify-desktop/config.toml file
```
[gotify]
url = "wss://EXAMPLE.com/gotify/stream"
token = "XXXXXXXXXXXX"

[notification]
min_priority = 0
```

Of course replace EXAMPLE.com with the correct domain, and replace the token.

**Comment by kwadroke** [comment]
`RUST_BACKTRACE=1` gives the same information

**Comment by kwadroke** [comment]
if I hard code my subpath into [src/gotify.rs line 182](https://github.com/desbma/gotify-desktop/blob/744680352ca8593f28e686fcb45c00a6f960fa2e/src/gotify.rs#L182) it works

`let url = base_url.to_owned().join("/gotify/application")?;`

**Comment by desbma** [comment]
Thanks for testing this project so quickly after I released it. :tada: 

It should be fixed now.

**Comment by kwadroke** [comment]
Thank you. Will give it a go shortly.

**Comment by desbma** [comment]
Actually, don't test it yet, it's broken.

**Comment by desbma** [comment]
It should **really** be fixed now.

I got bitten by https://github.com/servo/rust-url/issues/333
