### ISSUE TITLE
gotify-desktop exits when losing connection to gotify server

### ISSUE THREAD

**Issue by hell-g** [desbma/gotify-desktop#11]
I run a daily backup of my server which stops the gotify server before performing the backup and then starts the service again after the backup has been completed. If gotify-desktop is running on my desktop during the backup of the server, gotify-desktop exits and needs to be restarted manually to receive notifications again. 
Here is the output of gotify-desktop when the gotify server stops because of the backup:
```
$ gotify-desktop 
INFO  [gotify_desktop] Connected to wss://gotify.mydomain/
Error: Failed to get message

Caused by:
    WebSocket protocol error: Connection reset without closing handshake
```
Is this the expected behavior? What can I do to prevent this or restart gotify-desktop automatically? I am using a Gnome `.desktop` file to autostart gotify-desktop when I log in to my desktop.

**Comment by desbma** [comment]
I actually noticed the same issue in my own setup recently, it should be fixed by 4c5256b.
