### ISSUE TITLE
unexpected* behaviour when receiving irregular priorities

### ISSUE THREAD

**Issue by Robotix-00** [desbma/gotify-desktop#12]
By playing a little with the curl command an my gotify server, I've found that this client reacts a little weired when prompted with priorities outside its expected range (0-10). For any priority greater than 10 (e.g. 11), the app simply crashes with the error code 1 and the error message:
```
Error: Failed to handle message

Caused by:
    Unexpected urgency value 11
```

Due to rusts very literal approach to error handeling, this seems to be by design (which is the reason for the asterisk in the title):
https://github.com/desbma/gotify-desktop/blob/f49c5d7a3c8270cc4d38511a804e7f3eb03382ba/src/notif.rs#L8-L13

For any number below 0, the app does neither crash nor display the message, but doesn't do anything. (although I'm not entirely sure why)

I would propose to default to the "Normal" urgency if any numbers outside the expected range is received. In those cases, one could also consider to concatenate the message text by a note stating the priority, so that no data is lost.
If this behaviour is like this by design, appoligize for wasting your time. I do realise that specificly crafted messages like this rarely appear in real life szenarions but I do think that a simple irregular message shouldn't crash an entire app.

**Comment by desbma** [comment]
> I do think that a simple irregular message shouldn't crash an entire app.

This is a valid argument. I have changed it in bc9e45eab2357ab3a01f5dff24c1ddc9769f8f88 to warn and default to Normal priority if invalid.

> For any number below 0, the app does neither crash nor display the message, but doesn't do anything. (although I'm not entirely sure why)

It's due to the option `min_priority` which ignores notifications below a given priority, and which defaults to 0 when not set.
