### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by alcir** [desbma/gotify-desktop#14]
Hello.
I get this error

```
error[E0432]: unresolved import `nix::unistd::Uid`
  --> /usr/share/cargo/registry/zbus-3.14.1/src/address.rs:9:5
   |
9  | use nix::unistd::Uid;
   |     ^^^^^^^^^^^^^^^^ no `Uid` in `unistd`
   |
note: found an item that was configured out
  --> /usr/share/cargo/registry/nix-0.26.4/src/unistd.rs:73:12
   |
73 | pub struct Uid(uid_t);
   |            ^^^
   = note: the item is gated behind the `user` feature

error[E0432]: unresolved import `nix::unistd::Uid`
  --> /usr/share/cargo/registry/zbus-3.14.1/src/handshake.rs:4:5
   |
4  | use nix::unistd::Uid;
   |     ^^^^^^^^^^^^^^^^ no `Uid` in `unistd`
   |
note: found an item that was configured out
  --> /usr/share/cargo/registry/nix-0.26.4/src/unistd.rs:73:12
   |
73 | pub struct Uid(uid_t);
   |            ^^^
   = note: the item is gated behind the `user` feature

For more information about this error, try `rustc --explain E0432`.
error: could not compile `zbus` (lib) due to 2 previous errors
```

Hints: I'm not a developer; I'm trying to compile it using system libraries (on Fedora).
Thanks.

**Comment by desbma** [comment]
Please provide the full build log, the commands you are using to build, and how did you install Rust.

**Comment by alcir** [comment]
I attach what I can see with rpmbuild.
[rpmbuildgotifydesktop.txt](https://github.com/desbma/gotify-desktop/files/14303290/rpmbuildgotifydesktop.txt)

Rust is the one coming from the Fedora 39 repository.

**Comment by desbma** [comment]
It seems you are building under a special environment for the rpm packaging, for which I can not provide support.

If you simply build with `cargo build --release --locked` in a clean repository, does that succeed?

**Comment by alcir** [comment]
> If you simply build with `cargo build --release --locked` in a clean repository, does that succeed?

Eh. It builds successfully.

**Comment by alcir** [comment]
Eventually, adding
`nix = { version = "0.26", default-features = false, features = ["user"] }`
to Cargo.toml, also rpmbuild is successful.
What do you think?

Thanks.

**Comment by desbma** [comment]
`gotify-desktop` does not depend directly on `nix`, it's an indirect dependency, you should not have to fiddle with that.

As you saif yourself, it build successfully if building normally. If you choose to interfere with the dependencies and their resolution with a third party tool or changes in `Cargo.{toml,lock}`, I can not provide support with that, you'd have to ask the author of the tool.

Closing since building with cargo as in the README works.
