### ISSUE TITLE
KDE Notifications are using binary name (or lowercase)...adjust?

### ISSUE THREAD

**Issue by OdinVex** [desbma/gotify-desktop#15]
Notifications in KDE show up with titles of "gotify-desktop". I'm not referring to content titles. Any chance of adjusting that to "Gotify" or "Gotify Desktop" or "Gotify-Desktop"? See attached (4K hiDPI, sorry) screenshot.

![Gotify-Desktop](https://github.com/desbma/gotify-desktop/assets/44311901/dd6bc948-984f-411e-9fbe-72fd9f25653a)

**Comment by desbma** [comment]
I'm not sure I have control over this, maybe it's KDE that shows the process sending the notification?

What do you get with `notify-send` for example by running `notify-send "test title" "test content"` in terminal?

**Comment by desbma** [comment]
Never mind, it should be fixed by e235c81399dfc9a91a72e8a6c4c2913f3fef807f.

**Comment by desbma** [comment]
The AUR package is tracking tagged releases, and I will only tag a (minor) version if someone has tested the changed (I use [Dunst](https://dunst-project.org/) and am not affected by the issue), so it's up to you.

**Comment by desbma** [comment]
It has a blank icon, and before the fix it was not blank ?

**Comment by desbma** [comment]
I can't help you there as I can't test/reproduce this issue, but maybe try replacing the SVG icon by one from another entry, or by a PNG to see if it's a rendering issue.

**Comment by desbma** [comment]
Any news on this?

**Comment by desbma** [comment]
I have updated the AUR package to `1.3.4-2` with PNG icons, please tell me if that works on your system.

(the package does not yet include the caching fix from #16)
