### ISSUE TITLE
[Bug] Cache is incorrect

### ISSUE THREAD

**Issue by OdinVex** [desbma/gotify-desktop#16]
I'm not sure why it but Gotify Desktop's cache is incorrect after a server wipe and restart. Cleaning out `~/.cache/gotify-desktop` fixes it. Perhaps a different method of caching would be appropriate, one that is self-correcting.

Edit: A quick glance shows it to be a reliance upon app indexing. Perhaps e-tag or 'if modified since' headers could be used in some part of the filename to help address it, 'app-#-ETAG' candidating and such.

**Comment by desbma** [comment]
Can you develop "cache is incorrect", do you mean corrupt file, incorrect icon? How does that manifest?

**Comment by desbma** [comment]
It should be fixed by 480a991ff3dafc9abda8a0742ccc38c24f8d9a1d.

If you change icons on the Gotify server, you only need to restart `gotify-desktop`.
