### ISSUE TITLE
Compilation error on mac

### ISSUE THREAD

**Issue by reisub0** [desbma/gotify-desktop#2]
```
Compiling gotify-desktop v1.1.2 (/Users/g/gotify-desktop)
error[E0599]: no method named `urgency` found for mutable reference `&mut Notification` in the current scope
  --> src/notif.rs:16:10
   |
16 |         .urgency(urgency);
   |          ^^^^^^^ method not found in `&mut Notification`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `gotify-desktop`

To learn more, run the command again with --verbose.
```

OS Version: macOS Big Sur 11.5.1
notify-rust Version that got pulled seems to be v4.5.2 which seems to have this line at the top, which is what I believe is the source of the trouble:
```
#[cfg(all(unix, not(target_os = "macos")))] use crate::{
    hints::{CustomHintType, Hint},
    urgency::Urgency,
    xdg,
};
```

Removing the line urgency seems to successfully compile

**Comment by desbma** [comment]
Thanks for the report, can you try https://github.com/desbma/gotify-desktop/commit/8cc4a3859a6e7fd5557fc3a4500a59254d444103 and see if it builds on Mac?

**Comment by reisub0** [comment]
Hi desbma, that did not work either, I believe you will have to use the `#[cfg]` attribute like in `notify_rs` as follows:
```
    #[cfg(all(unix, not(target_os = "macos")))] 
    notif.urgency(urgency);
```

I think that putting it as part of the macro will still cause all of the code paths to be compiled and that's the reason that fix doesn't work.

**Comment by reisub0** [comment]
I just rebuilt the code with the attribute instead and it builds succesfully

**Comment by desbma** [comment]
Thanks, I though `#[cfg]` was only for functions, attributes etc. but could no be used inline inside function code.

So https://github.com/desbma/gotify-desktop/commit/aba832221cfa6892c95e4735541f67a8733ba9c1 works?

**Comment by reisub0** [comment]
Yep! Reverified with that commit hash as well

**Comment by reisub0** [comment]
As to the attribute part, it appears that you can indeed use them almost everywhere in most of the interesting cases where one might want to use it - see [Expression Atrributes](https://doc.rust-lang.org/reference/expressions.html#expression-attributes) for more details.

Thanks for working so quickly on the fix!
