### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alcir** [desbma/gotify-desktop#20]
Hello.
Could you add the license to Cargo.toml metadata? 
Please could you clarify whether the license is GPL-3.0-or-later or GPL-3.0-only, this is not clear from the license text and README.

Thanks.

**Comment by desbma** [comment]
> Hello. Could you add the license to Cargo.toml metadata? 

https://github.com/desbma/gotify-desktop/issues/17#issuecomment-1981753926

> Please could you clarify whether the license is GPL-3.0-or-later or GPL-3.0-only, this is not clear from the license text and README.

I am not a lawyer, but [§14 of the license](https://www.gnu.org/licenses/gpl-3.0-standalone.html#section14) is pretty unambiguous to me. Unless you have "or later" after the license version, which you don't for this repository, it's GPLv3 "only".
