### ISSUE TITLE
Is there an exe format file that Windows 10 can run directly?

### ISSUE THREAD

**Issue by saresam** [desbma/gotify-desktop#9]
Is there an exe format file that Windows 10 can run directly?
Because I can't figure out how to install it to accept notifications on win10

**Comment by desbma** [comment]
It will most likely not compile on Windows, because I have never tested it and some dependencies may be Unix only.

I would be open to accept a PR that makes it build on Windows though.

**Comment by saresam** [comment]
Thank you very much. I'm looking forward to it.
